apiVersion: v1
kind: Service
metadata:
  name: pandaxrule
  labels:
    app.kubernetes.io/name: pandaxrule
spec:
  type: LoadBalancer
  ports:
    - port: 7791
      targetPort: 7791
      protocol: TCP
  selector:
    app.kubernetes.io/name: pandaxrule
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pandaxrule
  labels:
    app.kubernetes.io/name: pandaxrule
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pandaxrule
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pandaxrule
    spec:
      serviceAccountName: pandaxrule
      containers:
        - name: pandaxrule
          image: ccr.ccs.tencentyun.com/pandax/pandaxrule:v1.8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7791
              protocol: TCP

