apiVersion: v1
kind: Service
metadata:
  name: pandaxscreen
  labels:
    app.kubernetes.io/name: pandaxscreen
spec:
  type: LoadBalancer
  ports:
    - port: 7790
      targetPort: 7790
      protocol: TCP
  selector:
    app.kubernetes.io/name: pandaxscreen
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pandaxscreen
  labels:
    app.kubernetes.io/name: pandaxscreen
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pandaxscreen
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pandaxscreen
    spec:
      serviceAccountName: pandaxscreen
      containers:
        - name: pandaxscreen
          image: ccr.ccs.tencentyun.com/pandax/pandaxscreen:v1.9.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7790
              protocol: TCP

