apiVersion: v1
kind: Service
metadata:
  name: pandaxweb
  labels:
    app.kubernetes.io/name: pandaxweb
spec:
  type: LoadBalancer
  ports:
    - port: 7788
      targetPort: 7789
      protocol: TCP
  selector:
    app.kubernetes.io/name: pandaxweb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pandaxweb
  labels:
    app.kubernetes.io/name: pandaxweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pandaxweb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pandaxweb
    spec:
      serviceAccountName: pandaxweb
      containers:
        - name: pandaxweb
          image: ccr.ccs.tencentyun.com/pandax/pandaxweb:v1.9.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7789
              protocol: TCP

