apiVersion: v1
kind: Service
metadata:
  name: pandax
  labels:
    app.kubernetes.io/name: pandax
spec:
  type: LoadBalancer
  ports:
    - port: 7788
      targetPort: 7788
      protocol: TCP
    - port: 9001
      targetPort: 9001
      protocol: TCP
    - port: 9002
      targetPort: 9002
      protocol: TCP
    - port: 9003
      targetPort: 9003
      protocol: TCP
    - port: 8801
      targetPort: 8801
      protocol: TCP
    - port: 5060
      targetPort: 5060
      protocol: TCP
  selector:
    app.kubernetes.io/name: pandax
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pandax
  labels:
    app.kubernetes.io/name: pandax
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pandax
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pandax
    spec:
      serviceAccountName: pandax
      containers:
        - name: pandax
          image: ccr.ccs.tencentyun.com/pandax/pandax:v1.9.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7788
              protocol: TCP
            - containerPort: 9001
              protocol: TCP
            - containerPort: 9002
              protocol: TCP
            - containerPort: 9003
              protocol: TCP
            - containerPort: 8801
              protocol: TCP
            - containerPort: 5060
              protocol: TCP

